version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 6
    labels:
      - "dependencies"
      - "npm"
    commit-message:
      prefix: "chore(deps)"
    groups:
      npm-patch-minor:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
      npm-major:
        patterns:
          - "*"
        update-types:
          - "major"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 4
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore(ci)"
    groups:
      actions-patch-minor:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
      actions-major:
        patterns:
          - "*"
        update-types:
          - "major"
  - package-ecosystem: "pip"
    directory: "/admin/product_manager"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 4
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "chore(py-deps)"
    groups:
      pip-patch-minor:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
      pip-major:
        patterns:
          - "*"
        update-types:
          - "major"
